// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKBSvLcGYFrv1vUF0BoyNma7zWRjxJUaM',
    appId: '1:757479397174:web:cffee96a4d288fdec6c597',
    messagingSenderId: '757479397174',
    projectId: 'smartstudyplan-e7117',
    authDomain: 'smartstudyplan-e7117.firebaseapp.com',
    storageBucket: 'smartstudyplan-e7117.firebasestorage.app',
    measurementId: 'G-SCW0YS0DMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj-gBAQPf_kCbMf60zvG_7edX1N-EawT4',
    appId: '1:757479397174:android:06f705ee39c7d44cc6c597',
    messagingSenderId: '757479397174',
    projectId: 'smartstudyplan-e7117',
    storageBucket: 'smartstudyplan-e7117.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJdBOrMlFBDYmHR64KUkCuGevobUcWll8',
    appId: '1:757479397174:ios:d9c2383c4040b5e9c6c597',
    messagingSenderId: '757479397174',
    projectId: 'smartstudyplan-e7117',
    storageBucket: 'smartstudyplan-e7117.firebasestorage.app',
    androidClientId: '757479397174-jk8rrenji9dtbc714e7a0nufghu76b01.apps.googleusercontent.com',
    iosClientId: '757479397174-c11n38c1l41ur5tel5u07leqd9ed5t51.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudyPlan',
  );

}